on: [push]
name: benchmark
jobs:
  benchmark:
    name: Run benchmark on GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["latest"]
        cabal: ["latest"]
    steps:
      - uses: actions/checkout@v4
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal bench -v0 --benchmark-options="--output hs-git-gsub-benchmark-${{ github.sha }}.html" >> benchmark-results.txt
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: hs-git-gsub-benchmark-${{ github.sha }}.html
      - name: Post Benchmark Results as PR Comment
        if: ${{ github.event.issue.pull_request }}
        run: |
          COMMENT_BODY="## Benchmark Results on ${{ github.sha }}\n\`\`\`\n$(cat benchmark-results.txt)\n\`\`\`"
          POST_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X POST --data "{\"body\": \"$COMMENT_BODY\"}" $POST_URL
