on: [push]
name: lint
jobs:
  format:
    name: Check format on GHC ${{ matrix.ghc }} with ormolu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["latest"]
        cabal: ["latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - uses: haskell-actions/run-ormolu@v15
